# Generated by Django 4.2.8 on 2023-12-05 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author", models.CharField(max_length=100)),
                ("text", models.CharField(max_length=1000)),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("likes", models.IntegerField(default=0)),
                ("image", models.CharField(max_length=1000)),
            ],
        ),
    ]
